use_frameworks!

platform :ios, '10.0'

target 'TextileImage_Example' do
  pod 'TextileImage', :path => '../'

  target 'TextileImage_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
